name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copiar Contenido de repositorio
        uses: siva1024/scp-deployer@latest    
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }} 
          PORT: ${{ secrets.PORT }}
          source: "prueba1/prueba.doc"  
          target: "/var/" 
