name: Site deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code to workspace
      uses: actions/checkout@v2
    - name: Deploy to web server
      uses: horochx/deploy-via-scp@master
      with:
         local: prueba.docx
         remote: ${{ secrets.REMOTE }} 
         host: ${{ secrets.HOST }} 
         port: ${{ secrets.PORT }} 
         user: ${{ secrets.USER }} 
         key: ${{ secrets.KEY }} 
   
