name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@master
    - name: Copiar el contenido del repositorio con scp
      uses: ilCollez/ssh-scp-deploy@v1.1.0
      env:
        host: 192.168.88.129 # "example.com"
        port: 22 # 22
        username: root # "user"
        password: jorge1984 # "password"
      with:
        files: prueba1/prueba.docx
        remote-path: "/var/www/html"
