name: Deploy

on: [push]

jobs:
 
  deploy:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@master
      - name: Copiar Contenido de repositorio
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.SSHKEY }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "site/*"
          target: "/var/www/html"
