name: Site deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code to workspace
      uses: actions/checkout@v2
    - name: Deploy to web server
      uses: moonpathbg/scp_uploader@latest
      with:
          port: 22
          host: ${{ secrets.SERVER_ADDRESS }}
          origin: "./*"
          destination: "/home/${{ secrets.SERVER_USERNAME }}/"
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
   
