name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Copiar el contenido del repositorio con scp
      uses: ilCollez/ssh-scp-deploy@v1.1.0
      with:
       host: ${{ secrets.SSH_HOST }} 
       port: ${{ secrets.SSH_PORT }} 
       username: ${{ secrets.SSH_USER }}  
       password: ${{ secrets.SSH_PASSWORD }} 
       files: "prueba1/prueba.docx"
       remote-path: "/var/www/html"
       clean: true
