name: Site deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code to workspace
      uses: actions/checkout@v2
    - name: Deploy to web server
      uses: ilCollez/ssh-scp-deploy@v1.1.0
      with:
         host: 192.168.88.129
         port: 22
         username: root
         password: jorge1984
         files: "prueba.doxc"
         remote-path: "/var/www/html"
         clean: true
   
