name: Site deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code to workspace
      uses: actions/checkout@v2
    - name: Deploy to web server
      uses: moonpathbg/scp_uploader@latest
      with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key : ${{ secrets.SSH_KEY }}
          source: "prueba.docx"
          target: "/var/"
   
