name: Site deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code to workspace
      uses: actions/checkout@v2
    - name: Run sshpass-scp commands
      uses: youxingz/sshpass-scp-action@v3
      with:
         host: 192.168.88.129
         user: root
         pass: jorge1984
         port: 22
         src: ./**
         dist: /usr/local
   
