name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copiar Contenido de repositorio
        uses: ilCollez/ssh-scp-deploy@v1.1.0    
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }} 
          password: ${{ secrets.SSH_PASSWORD }}
          files: "prueba.doc*"  
          destination: "/var/www" 
