name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Copiar el contenido del repositorio con scp
      uses: dj-256/github-deploy@v1
      with:
        local: ./opt
        remote: /var/www/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
   
