name: Site deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code to workspace
      uses: actions/checkout@v2
    - name: Deploy to web server
      uses: nicklasfrahm/scp-action@main
      with:
          direction: upload
          host: 192.1268.88.129
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: prueba.doxc
          target: /var
   
