on:
    push
jobs:
  ping_url:
    runs-on: ubuntu-latest
    name: Ping URL
    steps:
      - name: Check the URL
        id: ping
        uses: keylightberlin/pagerdutyuptime@v1
        with:
           pagerduty_token: 'My Token'
           pagerduty_from: 'hello@keylight.de'
           endpoint: '192.168.88.129' 
