name: Deploy
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: 192.168.88.129
        USERNAME: root
        PORT: 22
        KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkVl+uGxyO40lKGyhiLKKKNNIBoY0EGu4eBSl+Ai9RX/64Uh0dAgptHNTvHYJ4LAVS4z65HNfWcPAEpdndY4+eKCPbO5uGgyYijIQ7XKcOJmxEYPCQ3qhrXMy4FqXEhYDDYZC/uqQEsxggIU34G2uQ2pXexHkmXcmNFeZtVDrUSbCi1k84kL/ny+ZvoYXS6prBDTE12cJEEuiZW9R+UY9zXvXfzPC/FZASP3myzcRs/l5QcvUCaW1cPOfr8YYd6cWE17DsG7lHfXUEJ9DAA7NnTfRXCi6Vkqc3iTYaDfTcUUL4zvOzDHuwj4WpdzhW2vaB13D7y4r+rjjx8bxKI1R9 root@localhost.localdomain

        
      with:
        source: "."
        target: /var
